language: go
  go:
    - "1.10"

sudo: false

install:
  - # Skip

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - if [[ "$LATEST" = true ]]; then go tool vet .; fi
  - go test -v -race ./...
